import Link from "next/link";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { ensureDefaultWorkspace } from "@syntheci/db";
import { loadOperationalJobs } from "@/lib/voyage-workflows";

export const dynamic = "force-dynamic";

type SearchParams = Promise<Record<string, string | string[] | undefined>>;

export default async function TasksPage({ searchParams }: { searchParams: SearchParams }) {
  const params = await searchParams;
  const status = getParam(params.status);
  const workspaceId = await ensureDefaultWorkspace();
  const tasks = await loadOperationalJobs(workspaceId, status);

  return (
    <div className="space-y-5">
      <section className="rounded-lg border border-slate-200 bg-white p-5">
        <h1 className="text-xl font-semibold text-slate-950">Operational Tasks</h1>
        <p className="mt-1 text-sm text-slate-500">Voyage work items generated by missing-document, risk, claims, payment, and watchlist workflows.</p>
        <div className="mt-4 flex flex-wrap gap-2">
          {["open", "in_progress", "resolved", "dismissed"].map((item) => (
            <Button asChild key={item} size="sm" variant={status === item ? "default" : "outline"}>
              <Link href={`/workspace/tasks?status=${item}`}>{formatLabel(item)}</Link>
            </Button>
          ))}
          <Button asChild size="sm" variant={!status ? "default" : "outline"}>
            <Link href="/workspace/tasks">All</Link>
          </Button>
        </div>
      </section>

      <section className="overflow-hidden rounded-lg border border-slate-200 bg-white">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Task</TableHead>
              <TableHead>Voyage</TableHead>
              <TableHead>Type</TableHead>
              <TableHead>Priority</TableHead>
              <TableHead>Status</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {tasks.map((task) => (
              <TableRow key={task.id}>
                <TableCell>
                  <Link className="font-medium text-slate-950 hover:text-blue-700" href={`/workspace/tasks/${task.id}`}>
                    {task.title}
                  </Link>
                  <div className="mt-1 line-clamp-1 text-xs text-slate-500">{task.summary}</div>
                </TableCell>
                <TableCell>
                  <Link className="text-sm font-medium text-blue-700" href={`/workspace/voyages/${task.voyageId}`}>
                    {task.voyageId}
                  </Link>
                </TableCell>
                <TableCell>{formatLabel(task.jobType)}</TableCell>
                <TableCell>
                  <Badge variant="outline">{task.priority}</Badge>
                </TableCell>
                <TableCell>
                  <Badge variant="outline">{formatLabel(task.status)}</Badge>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </section>
    </div>
  );
}

function getParam(value: string | string[] | undefined) {
  return Array.isArray(value) ? value[0] : value;
}

function formatLabel(value: string) {
  return value.replace(/[_-]+/g, " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
}
